# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded crypt 1.0 [list tclPkgSetup $dir crypt 1.0 {{crypt.so load crypt}}]
package ifneeded limit 1.0 [list tclPkgSetup $dir limit 1.0 {{limit.so load limit}}]
package ifneeded setuid 1.0 [list tclPkgSetup $dir setuid 1.0 {{setuid.so load setuid}}]
package ifneeded utime 1.0 [list tclPkgSetup $dir utime 1.0 {{utime.so load utime}}]
